### PR TITLE
Add quantile bins

### PR DESCRIPTION
**Pull request by LaureFeuillet**
#### Why 
When we have outliers, using equal-width bins may induce a reduction of accuracy. 
Bins containing the same number of data, quantile bins, increase the resolution of shape functions in the region of interest.
This change is also suggested in issue https://github.com/microsoft/interpret/issues/42. 
#### How 
Add the parameter `binning_strategy` to the `ExplainableBoostingRegressor`. It can take two values for now : 
- `'uniform'` to make equal-width bins
- `'quantile'` to make bins having same number of data

Names are inspired by `KBinsDiscretizer` from scikit-learn.

### CODE REVIEW

**Comment by interpret-ml** [comment]
Hi @LaureFeuillet,

This looks great -- thanks for taking the initiative and making a PR! We'll try to get back to you in the next couple days. 

-InterpretML Team

**Comment by LaureFeuillet** [comment]
Hi @interpret-ml, 
Just rebased on version 0.1.12.

**Comment by interpret-ml** [comment]
Hi @LaureFeuillet,

Had a look at the code, seems great!
We'll add some minor changes (i.e. `cont_n_bins` will be renamed to `max_n_bins`) and merge this in ready for the next release.

**Comment by interpret-ml** [comment]
Ignore the build failure, this isn't related to your code, it's an anomaly with how GitHub and Azure DevOps cooperate.
The code merges in fine. :)

**Comment by LaureFeuillet** [comment]
Thanks for your work :)

**Pull request merged**
